import type { CampaignDefinition } from './campaignSchema'

export const firstCampaign: CampaignDefinition = {
  id: 'fjordglimt-first-journey',
  version: 3,
  contentProfile: 'public',
  title: 'Fjordglimt: Fra behov til trygg avslutning',
  summary:
    'En liten, syntetisk kampanje som gjør hele aktørreisen synlig uten å lære bort uverifiserte tekniske regler.',
  scenarioOrganisation: 'Fjordglimt kommune',
  stages: [
    {
      id: 'discover',
      sequence: 1,
      label: 'Oppdage',
      zone: 'Visningshallen',
      informationLevel: 'N1',
      objective:
        'Beskriv behovet, den viktigste målgruppen og hvorfor situasjonen er verdt å undersøke.',
      ownerRole: 'Tjenesteteam',
      entryCriteria: ['En konkret, syntetisk situasjon er valgt.'],
      exitEvidence: ['Behovsbeskrivelse', 'Primær målgruppe'],
      gate: {
        kind: 'missing-fact',
        question: 'Er behovet og den berørte målgruppen tydelig beskrevet?',
        successCondition: 'Behov og målgruppe er konkrete uten å låse teknisk løsning.',
      },
      requiredRuleIds: [],
      nextStageId: 'understand-assess',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'understand-assess',
      sequence: 2,
      label: 'Forstå og vurdere',
      zone: 'Speilsalen',
      informationLevel: 'N1',
      objective:
        'Undersøk forventet verdi, berørte roller, usikkerhet og viktige rammer før bestilling.',
      ownerRole: 'Behovseier',
      entryCriteria: ['Et forståelig behov og en målgruppe er dokumentert.'],
      exitEvidence: ['Aktørbilde', 'Vurdering av verdi og usikkerhet'],
      gate: {
        kind: 'missing-fact',
        question: 'Har laget nok innsikt til å forklare verdi, roller og usikkerhet?',
        successCondition: 'Vurderingen synliggjør både forventet verdi og åpne spørsmål.',
      },
      requiredRuleIds: [],
      nextStageId: 'clarify-order',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'clarify-order',
      sequence: 3,
      label: 'Avklare og bestille',
      zone: 'Ansvarslageret',
      informationLevel: 'N2',
      objective:
        'Avklar omfang, ansvar, avhengigheter og hva som må være sant før arbeid bestilles.',
      ownerRole: 'Bestiller',
      entryCriteria: ['Verdi, usikkerhet og sentrale aktører er vurdert.'],
      exitEvidence: ['Avklart omfang', 'Eiere og avhengigheter', 'Neste beslutning'],
      gate: {
        kind: 'unresolved-decision',
        question: 'Er ansvar og bestillingsgrunnlag tydelig nok til neste steg?',
        successCondition: 'Omfang, eiere, avhengigheter og åpne beslutninger er synlige.',
      },
      requiredRuleIds: [
        'co-purpose-legal-basis',
        'co-risk-dpia',
        'co-need-before-connection',
      ],
      nextStageId: 'connect',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'connect',
      sequence: 4,
      label: 'Koble på',
      zone: 'Forbindelsesbroen',
      informationLevel: 'N2',
      objective:
        'Finn riktig samarbeidsvei på grunnlag av det avklarte behovet og dokumenterte avhengigheter.',
      ownerRole: 'Samhandlingsansvarlig',
      entryCriteria: ['Bestillingsgrunnlag og ansvar er avklart.'],
      exitEvidence: ['Valgt samarbeidsvei', 'Bekreftede kontakt- og beslutningspunkter'],
      gate: {
        kind: 'invalid-choice',
        question: 'Følger valgt vei av scenarioet og de avklarte rammene?',
        successCondition: 'Valget kan forklares med behov, rammer og avhengigheter.',
      },
      requiredRuleIds: [
        'cn-helseid-suitability',
        'cn-helseid-production',
        'cn-helseid-client',
        'cn-fhir-conformance',
        'cn-smart-launch',
      ],
      nextStageId: 'design-build',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'design-build',
      sequence: 5,
      label: 'Designe og bygge',
      zone: 'Verkstedet',
      informationLevel: 'N3',
      objective:
        'Lag en løsning mot godkjent omfang med sporbare valg og tydelig ansvar for endringer.',
      ownerRole: 'Leveranseteam',
      entryCriteria: ['Samarbeidsvei og beslutningspunkter er bekreftet.'],
      exitEvidence: ['Sporbare designvalg', 'Byggeresultat mot avtalt omfang'],
      gate: {
        kind: 'evidence-check',
        question: 'Kan laget vise hva som er bygget og hvorfor valgene ble tatt?',
        successCondition: 'Byggeresultat og beslutninger kan spores til godkjent omfang.',
      },
      requiredRuleIds: [
        'db-privacy-default',
        'db-access-audit',
        'db-encryption-integrity',
      ],
      nextStageId: 'test-assure',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'test-assure',
      sequence: 6,
      label: 'Teste og kvalitetssikre',
      zone: 'Prøvekammeret',
      informationLevel: 'N3',
      objective:
        'Prøv forventet bruk, feilveier og avtalte kvalitetskrav og gjør resultatene forståelige.',
      ownerRole: 'Kvalitetsansvarlig',
      entryCriteria: ['Et sporbar byggeresultat er klart for prøving.'],
      exitEvidence: ['Testresultater', 'Avvik og tiltak', 'Forståelig kvalitetsstatus'],
      gate: {
        kind: 'evidence-check',
        question: 'Viser testbeviset både forventet bruk og relevante feilveier?',
        successCondition: 'Resultater, avvik, tiltak og gjenstående usikkerhet er dokumentert.',
      },
      requiredRuleIds: [],
      nextStageId: 'operate',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'operate',
      sequence: 7,
      label: 'Forvalte',
      zone: 'Vokterposten',
      informationLevel: 'N2',
      objective:
        'Gjør eierskap, støtte, oppfølging og håndtering av uønskede hendelser tydelig.',
      ownerRole: 'Tjenesteeier',
      entryCriteria: ['Kvalitetsstatus og gjenstående usikkerhet er kjent.'],
      exitEvidence: ['Forvaltningsansvar', 'Støtte- og oppfølgingsplan'],
      gate: {
        kind: 'unresolved-decision',
        question: 'Er ansvar og oppfølging forståelig før løsningen tas i bruk?',
        successCondition: 'Eier, støtte, oppfølging og eskalering er tydelig fordelt.',
      },
      requiredRuleIds: [],
      nextStageId: 'follow-up-improve',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'follow-up-improve',
      sequence: 8,
      label: 'Følge opp og forbedre',
      zone: 'Læringshagen',
      informationLevel: 'N2',
      objective:
        'Sammenlign faktisk erfaring med det opprinnelige behovet og velg forbedring med begrunnelse.',
      ownerRole: 'Forbedringsansvarlig',
      entryCriteria: ['Løsningen har tydelig eier og et avtalt oppfølgingspunkt.'],
      exitEvidence: ['Tilbakemelding mot behov', 'Prioritert forbedring eller begrunnet videreføring'],
      gate: {
        kind: 'evidence-check',
        question: 'Er forbedringen begrunnet med erfaring og det opprinnelige behovet?',
        successCondition: 'Valgt forbedring eller videreføring har synlig evidens og eier.',
      },
      requiredRuleIds: [],
      nextStageId: 'close',
      sourceIds: ['strategy-journey'],
    },
    {
      id: 'close',
      sequence: 9,
      label: 'Avslutte',
      zone: 'Avslutningsporten',
      informationLevel: 'N2',
      objective:
        'Avslutt eller overfør arbeidet kontrollert og gjør læring, ansvar og gjenstående oppgaver synlige.',
      ownerRole: 'Avslutningsansvarlig',
      entryCriteria: ['Erfaring, forbedringsvalg og videre ansvar er kjent.'],
      exitEvidence: ['Avslutnings- eller overføringsbeslutning', 'Læringsoppsummering'],
      gate: {
        kind: 'evidence-check',
        question: 'Er avslutning, overføring og læring tydelig dokumentert?',
        successCondition: 'Beslutning, eierskap og læring kan forstås av neste ansvarlige.',
      },
      requiredRuleIds: [],
      nextStageId: null,
      sourceIds: ['strategy-journey'],
    },
  ],
}
